name: Deploy to Vercel

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    # Skip nếu actor là chính repo owner
    if: github.actor == 'nguyenngoc200'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set Git config and amend if needed
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "nguyenngoc200"
          git config --global user.email "anh1922000@gmail.com"

          # Check current author
          current_author=$(git log -1 --pretty=format:'%an <%ae>')
          target_author="nguyenngoc200 <anh1922000@gmail.com>"

          if [ "$current_author" != "$target_author" ]; then
            echo "Amending commit author..."
            git commit --amend --reset-author --no-edit
            git remote set-url origin https://x-access-token:${TOKEN}@github.com/${{ github.repository }}.git
            git push --force
          else
            echo "Author already correct, no changes needed"
          fi
