name: Test and Deploy

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install

      - name: Run linting
        run: npm run lint

      - name: Build project
        run: npm run build

  deploy:
    needs: test # Chỉ chạy khi test pass
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # to allow rewriting history if needed

      - name: Set standard Git user info
        run: |
          git config --global user.name "Production Deployment"
          git config --global user.email "admin@lumines.io"

      - name: Amend last commit author (optional)
        run: |
          git commit --amend --reset-author --no-edit || echo "No changes to amend"

      - name: Push amended commit back
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git remote set-url origin https://x-access-token:${TOKEN}@github.com/${{ github.repository }}.git
          git push --force
